require "options"
require "keymaps"
require "plugins"
require "treesitter"
require "lualineconf"
require "blanklineconf"
require "lsp"
require "masonconf"
require "colorizerconf"
vim.cmd "colorscheme nightfox"
