return {
    'nvim-lua/plenary.nvim',
    'lewis6991/gitsigns.nvim',
    'tpope/vim-repeat',
    'tpope/vim-sensible',
    'tpope/vim-vinegar',
    { "JoosepAlviste/nvim-ts-context-commentstring", lazy = true },
    {
        'nvim-telescope/telescope.nvim',
        tag = '0.1.1',
        dependencies = { 'nvim-lua/plenary.nvim' }
    },
    'norcalli/nvim-colorizer.lua',
    'neovim/nvim-lspconfig',
    'williamboman/mason.nvim',
    'williamboman/mason-lspconfig.nvim',
    'hrsh7th/nvim-cmp',
    'hrsh7th/cmp-buffer',
    'hrsh7th/cmp-path',
    'saadparwaiz1/cmp_luasnip',
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-nvim-lua',
    'onsails/lspkind-nvim',
    'L3MON4D3/LuaSnip',
    'rafamadriz/friendly-snippets',
    'VonHeikemen/lsp-zero.nvim',
    { "nvim-tree/nvim-web-devicons", lazy = true },
    'folke/lsp-colors.nvim',
    'folke/trouble.nvim',
    'David-Kunz/markid',
    'Vimjas/vim-python-pep8-indent',
    {'sainnhe/gruvbox-material', lazy = true},
    {'navarasu/onedark.nvim', lazy = true},
    {'ellisonleao/gruvbox.nvim', lazy = true},
    {'cocopon/iceberg.vim', lazy = true},
    {'rebelot/kanagawa.nvim', lazy = true},
    {'ntk148v/vim-horizon', lazy = true},
    {'catppuccin/nvim', lazy=true, name = 'catppuccin'},
    {'EdenEast/nightfox.nvim', lazy=true, tag = 'v1.0.0'},
    {'olivercederborg/poimandres.nvim', lazy=true},
    { "MunifTanjim/nui.nvim", lazy = true },
}
